/*
  V2__create_messages.sql

  messages table
  - numeric role codes
  - BIGINT epoch timestamps
  - UUIDs generated by application
  - admin‑safe DDL (no extensions, no triggers)
*/

CREATE TABLE IF NOT EXISTS messages (
  -- Identifiers
  id UUID PRIMARY KEY,

  conversation_id UUID NOT NULL,
  user_id UUID NOT NULL,

  -- FK → graph_state.id
  graph_state_id UUID
    REFERENCES graph_state(id)
    ON DELETE SET NULL,

  /*
    Role codes:
      1 = USER
      2 = ASSISTANT
      3 = SYSTEM
  */
  role SMALLINT NOT NULL
    CHECK (role IN (1, 2, 3)),

  -- Message content
  message TEXT NOT NULL,

  -- Optional structured metadata
  metadata JSONB,

  -- Epoch milliseconds (LONG)
  created_at BIGINT NOT NULL
);

-- Conversation history queries
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id
  ON messages(conversation_id);

-- Multi‑user filtering
CREATE INDEX IF NOT EXISTS idx_messages_user_id
  ON messages(user_id);

-- Graph replay / tracing
CREATE INDEX IF NOT EXISTS idx_messages_graph_state_id
  ON messages(graph_state_id);

-- Time‑ordered messages
CREATE INDEX IF NOT EXISTS idx_messages_created_at
  ON messages(created_at);
