/*
  V1__create_graph_state.sql
  - Autogenerated UUID for ID
  - String-based conversation/user IDs (TEXT)
  - BIGINT epoch timestamps (milliseconds)
*/

CREATE TABLE IF NOT EXISTS graph_state (
  -- Matches Generated<string>
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Matches string (TEXT is the Postgres standard for strings)
  conversation_id TEXT NOT NULL,
   -- Foreign Key link to Users table
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  /*
    Status codes:
      1 = RUNNING, 2 = WAITING_FOR_USER, 3 = COMPLETED, 4 = FAILED
  */
  status SMALLINT NOT NULL 
    CHECK (status IN (1, 2, 3, 4)),

  -- Execution tracking (Matches number | null)
  current_node INTEGER,
  last_agent INTEGER,

  -- Full LangGraph snapshot (Matches unknown/JSONB)
  state JSONB NOT NULL DEFAULT '{}'::jsonb,

  error_message TEXT,

  -- Matches Generated<bigint> (Default to current epoch millis)
  created_at BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000)::BIGINT,
  updated_at BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000)::BIGINT
);

-- Indices for performance
CREATE INDEX IF NOT EXISTS idx_graph_state_conversation_id ON graph_state(conversation_id);
CREATE INDEX IF NOT EXISTS idx_graph_state_user_id ON graph_state(user_id);
CREATE INDEX IF NOT EXISTS idx_graph_state_status ON graph_state(status);
CREATE INDEX IF NOT EXISTS idx_graph_state_created_at ON graph_state(created_at);
