/*
  V2__create_messages.sql
  - Autogenerated UUID for ID
  - String-based IDs (TEXT) to match Kysely 'string'
  - BIGINT epoch timestamps (milliseconds)
  - Foreign Key to graph_state.id
*/

CREATE TABLE IF NOT EXISTS messages (
  -- Matches Generated<string>
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Matches string (using TEXT for flexibility with app-side strings)
  conversation_id TEXT NOT NULL,
  user_id TEXT NOT NULL,

  -- Matches string | null
  -- Link to graph_state (ensure graph_state.id is also UUID)
  graph_state_id UUID 
    REFERENCES graph_state(id) 
    ON DELETE SET NULL,

  /*
    Role codes:
      1 = USER, 2 = ASSISTANT, 3 = SYSTEM
  */
  role SMALLINT NOT NULL
    CHECK (role IN (1, 2, 3)),

  -- Message content
  message TEXT NOT NULL,

  -- Optional metadata (Matches unknown | null)
  metadata JSONB DEFAULT '{}'::jsonb,

  -- Matches Generated<bigint> (Default to current epoch millis)
  created_at BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000)::BIGINT
);

-- Indexing for chat history performance
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_user_id ON messages(user_id);
CREATE INDEX IF NOT EXISTS idx_messages_graph_state_id ON messages(graph_state_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at);
