/* Enable PgVector */
CREATE EXTENSION IF NOT EXISTS vector;

/*
  vector_documents table
  - Autogenerated UUIDs
  - String-based user_id (TEXT)
  - BIGINT timestamps (Epoch millis)
*/
CREATE TABLE IF NOT EXISTS vector_documents (
  -- Autogenerated ID to match Generated<string>
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- user_id as String/Text
  user_id TEXT NOT NULL,

  -- Raw content
  content TEXT NOT NULL,

  -- Vector embedding (pgvector: 736 dims)
  embedding VECTOR(736) NOT NULL,

  -- Semantic categorization (Nullable to match string | null)
  domain VARCHAR(50),
  facet VARCHAR(50),
  source VARCHAR(50),

  -- Flexible metadata
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,

  -- Versioning & lifecycle
  embedding_model VARCHAR(100) NOT NULL,
  embedding_version INTEGER NOT NULL DEFAULT 1,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,

  -- Timestamps as BIGINT to match Generated<bigint>
  created_at BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000)::BIGINT,
  updated_at BIGINT NOT NULL DEFAULT (extract(epoch from now()) * 1000)::BIGINT
);

-- Indices for performance
CREATE INDEX IF NOT EXISTS idx_vector_documents_user_id ON vector_documents(user_id);
CREATE INDEX IF NOT EXISTS idx_vector_documents_is_active ON vector_documents(is_active);
CREATE INDEX IF NOT EXISTS idx_vector_documents_created_at ON vector_documents(created_at);

-- Vector Similarity Index
CREATE INDEX IF NOT EXISTS idx_vector_documents_embedding
  ON vector_documents
  USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);
